### PR TITLE
Only remove non-removed paths (fixes #41).

### LINKED ISSUE #41: 1.6.1: Strange NodePath error, not present with 1.6.0
Firstly, thanks for creating this plugin! I've found it incredibly useful.

However when adding `v1.6.1` to a project recently, we got this strange error when running babel:
`NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)`.

However, `v1.6.0` does not have the issue. I'm guessing the `package-lock.json` added alongside `v1.6.1` locked down a dodgy babel dependancy?

Might be worth regenerating a fresh package lock?

### PR DESCRIPTION
**Pull request by phyllisstein**
This seems like the simplest fix to #41 that I can think of---though N.B. that I'm still not sure what caused the error in the first place. 🙁

### CODE REVIEW

**Comment by megawac** [comment]
Sorry for the delay, didn't look at this package for a while. @me if you need my attention :)

**Comment by megawac** [comment]
I'll also add you as an owner for this repo if you're interested on working on this project further.

**Comment by phyllisstein** [comment]
Thanks! Happy to be of use wherever I can.

**Comment by jazen** [comment]
@megawac Any plans for publishing a new version with this fix? I just ran into the issue myself.

**Comment by megawac** [comment]
Will do today

**Comment by megawac** [comment]
Published in https://github.com/megawac/babel-plugin-ramda/releases/tag/v1.6.2

**Pull request merged**
